### ISSUE TITLE
Optimised Code for Binary Search in C++ or Python

### ISSUE THREAD

**Issue by JOHN-72** [JOHN-72/Data-structure-and-algorithm#1]
NEED OPTIMIZED CODE FOR BINARY SEARCH

**Comment by Sakshi-75** [comment]
Hi @JOHN-72 ,
Can I work on this?

**Comment by JOHN-72** [comment]
Ya wait let me assign this to you

**Comment by arana2k** [comment]
can you assign this to me aslo i have got some idea regarding optimization with the help of fixing some bounds

**Comment by JOHN-72** [comment]
Done !!!

**Comment by JOHN-72** [comment]
Thanks for solving my Issue !
