### ISSUE TITLE
Need optimized code for given problem 

### ISSUE THREAD

**Issue by JOHN-72** [JOHN-72/Data-structure-and-algorithm#3]
Need optimized solution of given problem (preferable language-C++)

Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
An input string is valid if:
Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.

**Comment by beheradibas** [comment]
Hey @JOHN-72 ,

can you assign this issue to me ?

**Comment by arana2k** [comment]
It is similar to valid paranthesis problem , i know a optimal approach for this particular problem 
@JOHN-72 can you assign this issue to me ?

**Comment by JOHN-72** [comment]
ya @beheradibas @abhishek8778  you can work on this problem give me a sec let me assign this issue to you guys

**Comment by beheradibas** [comment]
I have added a Pull Request.

**Comment by JOHN-72** [comment]
Merged @beheradibas thanks for your contribution !!

**Comment by JOHN-72** [comment]
can you please a star on my repository, it will be really kindful of you

**Comment by JOHN-72** [comment]
Merged your solution too @abhishek8778 thanks for your contribution guys !!!!
